config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :categories do
    resources :tasks, except: [:index]
  end

  authenticated :user do
    root 'categories#index', as: :authenticated_root
  end
  get '/page-not-found', action: :error404, controller: 'landing_page'

  root to: 'landing_page#index'
  get "/users/password" => 'landing_page#error404'
  get "*path" => 'landing_page#error404'
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category
  belongs_to :user
  before_save { self.status = status.downcase }
  validates :title, presence: true
  validates :body, presence: true
  validates :status, presence: true
  validates :due_date, presence: true
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :handle_error
  #devise
  before_action :authenticate_user!,
                :find_task_by_id, except: [:new, :create]

  def new
    @task = Task.new()
    respond_to do |format|
      format.html
      format.js 
    end
  end

  def create
    @task = Task.new(task_params)
    @task.status = "new"
    @task.user_id = current_user.id
    @task.category_id = params[:category_id]
    @task.save

    if @task.save
      redirect_back fallback_location: categories_path, success: "Successfully created a task"
    else
      redirect_back fallback_location: categories_path, danger: "Kindly double check all information before submitting"
    end
    
  end

  def show
    respond_to do |format|
      format.html
      format.js 
    end
  end
  
  def edit
    respond_to do |format|
      format.html
      format.js 
    end
  end

  def update
    @task.update(task_params)

    if @task.update(task_params)
      redirect_back fallback_location: categories_path, success: "Successfully updated task"
    else
      redirect_back fallback_location: categories_path, danger: "Kindly double check all information before submitting"
    end
  end

  def destroy
    @task.delete

    if @task.delete
      redirect_back(fallback_location: categories_path, success: "Successfully updated task")
    else
      redirect_back(fallback_location: categories_path, success: "Error occured in deletion. Please try again.")
    end
  end

  private

  def task_params
    params.require(:task).permit(:title, :body, :status, :due_date)
  end

  def find_task_by_id
    @task = current_user.tasks.find(params[:id])
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_edit.html.erb
<div class="modal-header">
  <h5 class="modal-title" id="editTaskModalTitle">Edit Task</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  </div>
    <div class="modal-body">
      <%= form_with model: [:category, @task], method: :put do |form| %>
      <%= form.label :title, "Title" %>
      <%= form.text_field :title %>
      <%= form.label :body, "Description" %>
      <%= form.text_area :body %>
      <%= form.label :status, "Status" %>
      <%= form.select :status, options_for_select(["New", "Ongoing", "Completed"], selected: @task.status.capitalize) %>
      <%= form.label :due_date, "Due Date" %>
      <%= form.date_field :due_date, value: @task.due_date.strftime('%Y-%m-%d') %>
      <%= form.submit "Update", class: "submit" %>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/_new.html.erb
<div class="modal-header">
  <h5 class="modal-title" id="addTaskModalTitle">Add Task</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  </div>
    <div class="modal-body">
      <%= form_with model: [:category, @task], method: :post do |form| %>
      <%= form.label :title, "Title" %>
      <%= form.text_field :title %>
      <%= form.label :body, "Description" %>
      <%= form.text_area :body %>
      <%= form.label :due_date, "Due Date" %>
      <%= form.date_field :due_date, value: Time.now.strftime('%Y-%m-%d'), min: Date.today %>
      <%= form.submit "Create", class: "submit" %>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/_show.html.erb
<div class="modal-header">
  <h5 class="modal-title" id="showTaskModalTitle"><%= @task.title %></h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  </div>
    <div class="modal-body">
      <%= simple_format(@task.body) %>
      <h5>Due date: <%= @task.due_date.strftime("%b %d, %Y") %></h5>
    </div>
    <div class="modal-footer">
      
      <%= link_to 'Delete', category_task_path(category_id: @task.category_id, id: @task.id), method: :delete, class: "delete", data: {confirm: "Any progress on this task will be deleted once you confirm", commit: 'Delete'} %>
      <%= link_to 'Edit', edit_category_task_path(category_id: @task.category_id, id: @task.id), {remote: true, 'data-toggle' =>  "modal", 'data-target' => '#categoryModal', class: "edit", id: "taskEdit" } %>
      </div>
  </div>
</div>

app/views/tasks/edit.js.erb
$("#categoryModal").find(".modal-content").html("<%= j render partial: 'tasks/edit' %>");

app/views/tasks/new.html.erb
<h1>Create Task</h1>

<%= form_with model: [:category, @task], method: :post do |form| %>
  <%= form.text_field :title %>
  <%= form.text_area :body %>
  <%= form.date_field :due_date, value: Time.now.strftime('%Y-%m-%d') %>
  <%= form.submit "Create Task", class: "submit" %>
<% end %>

app/views/tasks/new.js.erb
$("#categoryModal").find(".modal-content").html("<%= j render partial: 'tasks/new' %>");

app/views/tasks/new_bkp.html.erb
<h1>Create Task</h1>

<%= form_with model: [:category, @task], method: :post do |form| %>
  <%= form.text_field :title %>
  <%= form.text_area :body %>
  <%= form.date_field :due_date, value: Time.now.strftime('%Y-%m-%d') %>
  <%= form.submit "Create Task", class: "submit" %>
<% end %>

app/views/tasks/show.js.erb
$("#showModal").find(".modal-content").html("<%= j render partial: 'tasks/show' %>");

$("#taskEdit").click(function() {
  $("#showModal").modal("hide")
})