config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :categories do
    resources :tasks, except: [:index]
  end

  authenticated :user do
    root 'categories#index', as: :authenticated_root
  end
  get '/page-not-found', action: :error404, controller: 'landing_page'

  root to: 'landing_page#index'
  get "/users/password" => 'landing_page#error404'
  get "*path" => 'landing_page#error404'
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy
  
  before_save { self.name = name.downcase }
  validates :name, presence: true, length: { maximum: 20 },
            uniqueness: { case_sensitive: false, scope: :user_id}

  validates :description, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :handle_error
  #devise
  before_action :authenticate_user!,
                :find_category_by_id, except: [:index, :new, :create]
  
  def index
    @categories = current_user.categories.all.order("id")
    @tasks = current_user.tasks.order("due_date")
    @tasks_today = current_user.tasks.all.where('due_date <= ?', DateTime.now).where.not(status: "completed").order("due_date ASC").order("due_date ASC")
  end

  def new
    @category = Category.new
    respond_to do |format|
      format.html
      format.js 
    end
  end

  def create
    @category = Category.new(category_params)
    @category.user_id = current_user.id
    @category.save
    if @category.save 
      #specify return redirect later
      redirect_to @category, success: "Category successfully created", fallback_location: categories_path
    else
      redirect_to @category, danger: "Invalid name or description", fallback_location: categories_path
    end
  end

  def show
    @categories = current_user.categories.all.order("id")
    @tasks = @category.tasks.order("due_date ASC")
    @current_category_id = params[:id]
    @tasks_today = @category.tasks.all.where('due_date <= ?', DateTime.now).where.not(status: "completed").order("due_date ASC")
  end

  def edit
    respond_to do |format|
      format.html
      format.js 
    end
  end

  def update
    @category.update(category_params)

    if @category.update(category_params)
      redirect_back(fallback_location: categories_path, success: "Category successfully updated")
    else
      redirect_back(fallback_location: categories_path, danger: "Invalid name or description")
    end
    
    
  end

  def destroy
    @category.destroy

    if @category.destroy
      redirect_to categories_path, success: "Category successfully deleted"
    else  
      redirect_back(fallback_location: categories_path, danger: "Error occured in deletion. Please try again.")
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :description)
  end

  def find_category_by_id
    @category = Category.find(params[:id])
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_edit.html.erb
<div class="modal-header">
  <h5 class="modal-title" id="editCategoryModalTitle">Edit Category</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  </div>
    <div class="modal-body">
      <%= form_with model: @category, method: :put do |form| %>
      <%= form.label :name, "Name" %>
      <%= form.text_field :name %>
      <%= form.label :description, "Description" %>
      <%= form.text_field :description %>
      <%= form.submit "Update", class: "submit" %>
      <% end %>
    </div>
  </div>
</div>

app/views/categories/_new.html.erb
<div class="modal-header">
  <h5 class="modal-title" id="addCategoryModalTitle">Add Category</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  </div>
    <div class="modal-body">
      <%= form_with model: @category, method: :post do |form| %>
      <%= form.label :name, "Name" %>
      <%= form.text_field :name %>
      <%= form.label :description, "Description" %>
      <%= form.text_field :description %>
      <%= form.submit "Create", class: "submit" %>
      <% end %>
    </div>
  </div>
</div>

app/views/categories/edit.js.erb
$("#categoryModal").find(".modal-content").html("<%= j render partial: 'categories/edit' %>");

app/views/categories/index.html.erb
<section class="container-planner">
  <div class="container-label">
    <div class="container-sub-label">
      <h1>Planner Dashboard</h1>
      <h3>My own dashboard</h3>
    </div>
  </div>

  <section class="container-main-body">
    <div class="container-header-section">
      <div class="container-header-stats">
        <div class="container-header-label">
          <h2>Categories</h2>
          <div class="add-category-container">
            <%= link_to '+ Add Category', new_category_path, {remote: true, 'data-toggle' =>  "modal", 'data-target' => '#categoryModal', class: "submit" } %>
          </div>
        </div>
        <div class="sub-container-header-stats-category">
          <% if @categories.nil? || @categories.count == 0%>
            <div class="category-card">
              <div class="category-data">
                <h2>Create category to begin your planning</h2>
              </div>
            </div>
          <% else %>
          <% @categories.each do |category| %>
              <%= render partial: 'components/category-card', locals: {category: category }%>
          <% end %>
          <% end %>
        </div>
      </div>
      <div class="container-header-stats">
        <div class="container-header-label">
          <h2>Status</h2>
        </div>
        <div class="sub-container-header-stats">
          <div class="category-card">
            <div class="category-data">
              <h3>New</h3>
            </div>
            <div class="category-data-actual">
              <h1><%= @tasks.where(status: "new").count %></h1>
            </div>
          </div>

          <div class="category-card">
            <div class="category-data">
              <h3>Ongoing</h3>
            </div>
            <div class="category-data-actual">
              <h1><%= @tasks.where(status: "ongoing").count %></h1>
            </div>
          </div>

          <div class="category-card">
            <div class="category-data">
              <h3>Completed</h3>
            </div>
            <div class="category-data-actual">
              <h1><%= @tasks.where(status: "completed").count %></h1>
            </div>
          </div>

          
        </div>
      </div>
    </div>
    
    <div class="container-body-section">
      <div class="container-label">
        <h2>Tasks due today</h2>
      </div>

      <div class="sub-container-task_cards due-today">
        <% if @tasks_today.nil? || @tasks_today&.count == 0 %>
          <div class="task-card-container">
            <h3>No tasks due for today</h3>
          </div>
        <% else %>
        <% @tasks_today.each do |task| %>
          <%= render partial: 'components/task-card', locals: {category_name: task.category.name, task: task} %>
        <% end %>
        <% end %>
      </div>

      <div class="container-label">
        <h2>Overall Tasks</h2>
      </div>

      <div class="sub-container-task_cards">
        
          <% if @tasks.nil? || @tasks&.count == 0 %>
            <div class="task-card-container">
              <h3>No tasks created</h3>
            </div>
          <% else %>
          <% @tasks.each do |task| %>
            <%= render partial: 'components/task-card', locals: {category_name: task.category.name, task: task} %>
          <% end %>
          <% end %>

        
      </div>
    </div>
    
  </section>

  
</section>

app/views/categories/new.js.erb
$("#categoryModal").find(".modal-content").html("<%= j render partial: 'categories/new' %>");

app/views/categories/show.html.erb
<section class="container-planner">
  <div class="container-label">
    <div class="container-sub-label">
      <h1><%= @category.name&.capitalize %></h1>
      <h3><%= @category.description&.capitalize %></h3>
    </div>
  </div>

  <section class="container-main-body">
    <div class="container-header-section">
      <div class="container-header-stats">
        <div class="container-header-label">
          <h2>Categories</h2>
          <div class="add-category-container">
            <%= link_to '+ Add Category', new_category_path, {remote: true, 'data-toggle' =>  "modal", 'data-target' => '#categoryModal', class: "submit" } %>
          </div>
        </div>
        <div class="sub-container-header-stats-category">
          <% @categories.each do |category| %>
              <%= render partial: 'components/category-card-show', locals: {category: category }%>
          <% end %>

          <%# end %>
        </div>
      </div>
      <div class="container-header-stats">
        <div class="container-header-label">
          <h2>Status</h2>
        </div>
        <div class="sub-container-header-stats">
          <div class="category-card">
            <div class="category-data">
              <h3>New</h3>
            </div>
            <div class="category-data-actual">
              <h1><%= @tasks.where(status: "new").count %></h1>
            </div>
          </div>

          <div class="category-card">
            <div class="category-data">
              <h3>Ongoing</h3>
            </div>
            <div class="category-data-actual">
              <h1><%= @tasks.where(status: "ongoing").count %></h1>
            </div>
          </div>

          <div class="category-card">
            <div class="category-data">
              <h3>Completed</h3>
            </div>
            <div class="category-data-actual">
              <h1><%= @tasks.where(status: "completed").count %></h1>
            </div>
          </div>

          
        </div>
      </div>
    </div>
    
    <div class="container-body-section">
      <div class="container-label">
        <h2>Tasks due today</h2>
        <div class="add-category-container">
            <%= link_to '+ Create Task', new_category_task_path(category_id: @category), {remote: true, 'data-toggle' =>  "modal", 'data-target' => '#categoryModal', class: "submit" } %>
          </div>
      </div>

      <div class="sub-container-task_cards">
        <% if @tasks_today.nil? || @tasks_today&.count == 0 %>
          <div class="task-card-container">
            <h3>No tasks due for today</h3>
          </div>
        <% end %>
        <% @tasks_today&.each do |task| %>
          <%= render partial: 'components/task-card', locals: {category_name: task.category.name, task: task} %>
        <% end %>
      </div>

      <div class="container-label">
        <h2>Overall Tasks</h2>
      </div>

      <div class="sub-container-task_cards">
        <% if @tasks.nil? || @tasks&.count == 0 %>
          <div class="task-card-container">
            <h3>No tasks created</h3>
          </div>
        <% end %>
        <% @tasks.each do |task| %>
          <%= render partial: 'components/task-card', locals: {category_name: task.category.name, task: task} %>
        <% end %>
      </div>
    </div>
    
  </section>

  
</section>